import { router, useForm } from '@inertiajs/react';

const field = 'w-full rounded-xl border-slate-200 bg-slate-50 px-4 py-3 text-sm font-bold focus:border-[#00d2d3] focus:ring-[#00d2d3]';
const Card = ({ title, subtitle, children }) => <section className="rounded-2xl border border-slate-100 bg-white p-6 shadow-sm"><h3 className="text-lg font-black">{title}</h3><p className="mt-1 text-xs text-slate-400">{subtitle}</p><div className="mt-5">{children}</div></section>;

export default function PlatformManagement({ platform, courses }) {
    const organization = useForm({ name: '', slug: '' });
    const cohort = useForm({ course_id: '', name: '', starts_on: '', ends_on: '', capacity: '' });
    const department = useForm({ name: '', code: '' });
    const session = useForm({ name: '', starts_on: '', ends_on: '', is_current: true });
    const banner = useForm({ title: '', subtitle: '', action_url: '', image: null });
    const api = async (path, data) => {
        const response = await fetch(`/platform${path}`, { method: 'POST', credentials: 'same-origin', headers: { Accept: 'application/json', 'Content-Type': 'application/json', 'X-CSRF-TOKEN': document.querySelector('meta[name="csrf-token"]')?.content }, body: JSON.stringify(data) });
        if (response.ok) router.reload();
        else alert((await response.json()).message || 'Unable to save.');
    };

    return <div className="space-y-6"><div><p className="text-[9px] font-black uppercase tracking-[.2em] text-[#087f81]">SaaS & enterprise</p><h2 className="mt-2 text-3xl font-black tracking-tight">Platform management</h2><p className="mt-2 text-sm text-slate-400">Manage your academy, cohorts, subscription, sessions, and mobile content.</p></div>
        <div className="grid gap-6 xl:grid-cols-2">
            <Card title="Organization" subtitle="The tenant boundary for users, courses, and academic data.">{platform.organization ? <div className="rounded-xl bg-[#e7fbfb] p-4"><p className="font-black">{platform.organization.name}</p><p className="text-xs text-[#087f81]">{platform.organization.slug}</p></div> : <form onSubmit={e => {e.preventDefault(); api('/organizations', organization.data)}} className="space-y-3"><input className={field} placeholder="Academy or school name" value={organization.data.name} onChange={e => organization.setData('name', e.target.value)} /><input className={field} placeholder="URL slug (optional)" value={organization.data.slug} onChange={e => organization.setData('slug', e.target.value)} /><button className="rounded-xl bg-[#1a1d21] px-5 py-3 text-xs font-black text-white">Create organization</button></form>}</Card>
            <Card title="Subscription" subtitle="Activate the plan that matches your institution."><div className="grid gap-2 sm:grid-cols-3">{platform.plans?.map(plan => <button key={plan.id} onClick={() => api('/subscriptions', { plan_id: plan.id })} disabled={!platform.organization} className="rounded-xl border p-4 text-left hover:border-[#00d2d3] disabled:opacity-40"><p className="text-xs font-black">{plan.name}</p><p className="mt-2 text-sm font-black text-[#087f81]">₦{Number(plan.price).toLocaleString()}</p></button>)}</div></Card>
            <Card title="Cohorts" subtitle="Group students around a course and schedule."><form onSubmit={e => {e.preventDefault(); api('/cohorts', cohort.data)}} className="grid gap-3 sm:grid-cols-2"><select className={field} value={cohort.data.course_id} onChange={e => cohort.setData('course_id', e.target.value)}><option value="">Select course</option>{courses.map(item => <option key={item.id} value={item.id}>{item.title}</option>)}</select><input className={field} placeholder="Cohort name" value={cohort.data.name} onChange={e => cohort.setData('name', e.target.value)} /><input type="date" className={field} value={cohort.data.starts_on} onChange={e => cohort.setData('starts_on', e.target.value)} /><input type="date" className={field} value={cohort.data.ends_on} onChange={e => cohort.setData('ends_on', e.target.value)} /><button className="rounded-xl bg-[#1a1d21] px-5 py-3 text-xs font-black text-white">Create cohort</button></form><div className="mt-4 space-y-2">{platform.cohorts?.map(item => <p key={item.id} className="rounded-xl bg-slate-50 p-3 text-xs font-bold">{item.name} · {item.status}</p>)}</div></Card>
            <Card title="Enterprise academics" subtitle="Create departments and academic sessions."><form onSubmit={e => {e.preventDefault(); api('/departments', department.data)}} className="flex gap-2"><input className={field} placeholder="Department" value={department.data.name} onChange={e => department.setData('name', e.target.value)} /><input className={`${field} max-w-28`} placeholder="Code" value={department.data.code} onChange={e => department.setData('code', e.target.value)} /><button className="rounded-xl bg-[#1a1d21] px-4 text-xs font-black text-white">Add</button></form><form onSubmit={e => {e.preventDefault(); api('/academic-sessions', session.data)}} className="mt-5 grid gap-2 sm:grid-cols-2"><input className={field} placeholder="2026/2027" value={session.data.name} onChange={e => session.setData('name', e.target.value)} /><input type="date" className={field} value={session.data.starts_on} onChange={e => session.setData('starts_on', e.target.value)} /><input type="date" className={field} value={session.data.ends_on} onChange={e => session.setData('ends_on', e.target.value)} /><button className="rounded-xl bg-[#00d2d3] px-4 py-3 text-xs font-black">Create session</button></form></Card>
            <Card title="Mobile banners" subtitle="Promotional images shown on the mobile home screen."><form onSubmit={e => { e.preventDefault(); banner.post('/admin/banners', { forceFormData: true, onSuccess: () => banner.reset() }); }} className="space-y-3"><input className={field} placeholder="Banner title" value={banner.data.title} onChange={e => banner.setData('title', e.target.value)} /><textarea className={field} placeholder="Short message" value={banner.data.subtitle} onChange={e => banner.setData('subtitle', e.target.value)} /><input type="file" accept="image/*" className={field} onChange={e => banner.setData('image', e.target.files[0])} /><button className="rounded-xl bg-[#1a1d21] px-5 py-3 text-xs font-black text-white">Publish banner</button></form><div className="mt-4 space-y-2">{platform.banners?.map(item => <div key={item.id} className="flex items-center justify-between rounded-xl bg-slate-50 p-3 text-xs font-bold"><span>{item.title}</span><button onClick={() => router.delete(`/admin/banners/${item.id}`)} className="text-red-500">Remove</button></div>)}</div></Card>
        </div>
    </div>;
}
